all:
	gcc -c FCFS.c
	gcc -c RR.c
	gcc -c PB.c
	gcc -c SJF.c
	gcc -c SJF_p.c
	gcc -c min.c
	gcc -c max.c
	gcc -c B18CSE022.c
	gcc -c avg.c
	g++ -o A A.cpp
	gcc FCFS.o RR.o PB.o SJF.o SJF_p.o min.o max.o avg.o B18CSE022.o -o driver